<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/localhost"/>
    <meta charset="UTF-8"/>
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>"/>
    <link rel="stylesheet" href="style.css" type="text/css"/>
</head>

<body>
<header>
    <h1>ICT.social MVC - Sample website</h1>
</header>

<nav>
    <?php if (isset($_SESSION['admin']) || isset($_SESSION['user'])): ?>
        <ul>
            <li><a href="home">Home</a></li>
            <li><a href="product">Product</a></li>
            <li><a href="contact">Contact</a></li>
            <li><a href="logout">Logout</a></li>
        </ul>
    <?php else: ?>
        <ul>
            <li><a href="login">Login</a></li>
        </ul>
    <?php endif; ?>
</nav>
<br clear="both"/>

<article>
    <?php $this->controller->renderView(); ?>
</article>

<footer>
    <p>
        Sample tutorial of a simple MVC from
        <a href="http://www.ict.social" target="_blank">ict.social</a> - The social network for programmers.
    </p>
</footer>
</body>
</html>
